// #define SPLIT_USB_TIMEOUT 5000
#define TAPPING_TERM 200
#define CTRL_TIMEOUT 1000
/* #define CTRL_TIMEOUT (TAPPING_TERM + 500) */
#define TAPPING_FORCE_HOLD
#define TAPPING_TERM_PER_KEY
#define PERMISSIVE_HOLD
// #define PERMISSIVE_HOLD_PER_KEY
#define QUICK_TAP_TERM 1

#define COMBO_SHOULD_TRIGGER


#define RGB_MATRIX_KEYRELEASES
#define RGB_MATRIX_FRAMEBUFFER_EFFECTS
#define RGB_MATRIX_DEFAULT_SPD 10
#define RGB_MATRIX_DEFAULT_HUE 182
#define RGB_MATRIX_DEFAULT_SAT 255
#define RGB_MATRIX_DEFAULT_VAL RGB_MATRIX_MAXIMUM_BRIGHTNESS

//Layout
#define RGB_LAYOUT_7 RGB_TURQUOISE
#define RGB_LAYOUT_6 RGB_PINK
#define RGB_LAYOUT_5 RGB_RED
#define RGB_LAYOUT_4 RGB_MAGENTA
#define RGB_LAYOUT_3 RGB_GREEN
#define RGB_LAYOUT_2 RGB_TURQUOISE
#define RGB_LAYOUT_1 RGB_CYAN
#define RGB_LAYOUT_0 RGB_PURPLE


#define HSV_LAYOUT_7 HSV_TURQUOISE
#define HSV_LAYOUT_6 HSV_PINK
#define HSV_LAYOUT_5 HSV_RED
#define HSV_LAYOUT_4 HSV_MAGENTA
#define HSV_LAYOUT_3 HSV_GREEN
#define HSV_LAYOUT_2 HSV_TURQUOISE
#define HSV_LAYOUT_1 HSV_CYAN
#define HSV_LAYOUT_0 HSV_PURPLE
