POINTING_DEVICE_ENABLE = false
AUDIO_ENABLE = false
ENCODER_ENABLE = no

TAP_DANCE_ENABLE = yes
COMBO_ENABLE = yes
LEADER_ENABLE = yes
KEY_OVERRIDE_ENABLE = yes
RGB_MATRIX_ENABLE = yes
ENCODER_MAP_ENABLE = yes
KEY_LOCK_ENABLE = yes
CONSOLE_ENABLE = yes
SRC += features/achordion.c
