#pragma once

#include "keymap.h"


enum key_override_ids {
    OVERRIDE_QUOTE_AST,
    OVERRIDE_QUOTE_GRAVE,
    OVERRIDE_SHIFT_9_0,
    OVERRIDE_SHIFT_LBRACKET_RBRACKET,
    OVERRIDE_LBRACKET_RBRACKET,
    OVERRIDE_SHIFT_COMMA_EQUAL,
    OVERRIDE_SHIFT_COMMA_DOT,
    OVERRIDE_SLASH_SHIFT7,
    OVERRIDE_SLASH_BSLASH_SHIFT,
    OVERRIDE_SLASH_BSLASH_AG,
    OVERRIDE_SHIFT_COMMA_GRAVE,
    OVERRIDE_F13_EXLM,
    OVERRIDE_F13_COMMA,
    OVERRIDE_F13_QUES,
    OVERRIDE_F13_DOT,
    OVERRIDE_RALT_B,
    KEY_OVERRIDE_COUNT
};

extern const key_override_t *key_overrides[KEY_OVERRIDE_COUNT] ;
void setup_key_overrides(void);
